# Generated by Django 5.2 on 2025-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='artist/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, help_text='указывать сумму в рублях', verbose_name='Цена')),
                ('image', models.ImageField(upload_to='painting/', verbose_name='Картина')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('artist', models.ManyToManyField(related_name='painting_artist', to='paintingapp.artist', verbose_name='художники')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
            },
        ),
    ]
