# Generated by Django 5.2 on 2025-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
