# Generated by Django 5.2 on 2025-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingapp', '0002_artist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='url',
        ),
        migrations.AddField(
            model_name='painting',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
