# Generated by Django 5.2 on 2025-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingapp', '0003_remove_artist_slug_remove_painting_url_painting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, default=1, max_length=11, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
