# Generated by Django 5.2 on 2025-05-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingapp', '0004_painting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, default=0, max_length=11, verbose_name='Номер телефона'),
        ),
    ]
