# Generated by Django 5.2 on 2025-05-12 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingapp', '0005_alter_painting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+7XXXXXXXXXX'. Допустимо до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Указывать сумму в рублях', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
